sudo: required

services:
  - docker

script:
  - mv ./travis.Dockerfile Dockerfile
  - docker build . -t nicekingwei/zju-lambda-web:travis
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push nicekingwei/zju-lambda-web